# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KRP <- function(A, B) {
    .Call(`_tensorApp_KRP`, A, B)
}

TuckerALS <- function(T1, d0, dims, rs, Dn, optsList) {
    .Call(`_tensorApp_TuckerALS`, T1, d0, dims, rs, Dn, optsList)
}

CPALS <- function(T0, d0, d, dims, D0, optsList) {
    .Call(`_tensorApp_CPALS`, T0, d0, d, dims, D0, optsList)
}

CPALS_dr <- function(T0, d0, d, dims, D0, optsList) {
    .Call(`_tensorApp_CPALS_dr`, T0, d0, d, dims, D0, optsList)
}

TransferModalUnfoldingsT <- function(T, d1, d2, dims) {
    .Call(`_tensorApp_TransferModalUnfoldingsT`, T, d1, d2, dims)
}

